### ISSUE TITLE
Swap dependency from momentjs to dayjs

### ISSUE THREAD

**Issue by ymsimei** [DonorDrive/StreamKit#6]
### Overview
Momentjs is no longer in active development. The only functionality needed by it are covered by the smaller dependency dayjs. This alternative can reduce first page load times and have a dependency in active development.

More info: https://momentjs.com/docs/#/-project-status/

**Comment by reverk** [comment]
Hi, can I give it a try on this?

It seems like [donation-ticker.html](https://github.com/DonorDrive/StreamKit/blob/master/donation-ticker.html) is the only file that depends on momentjs, is that correct?

**Comment by ymsimei** [comment]
@reverk, sorry about that! this is something anyone can do

**Comment by reverk** [comment]
@ymsimei Ah, thanks for clearing up the confusion! Can I give it a try on swapping it?
